### ISSUE TITLE
Please provide the Sources 

### ISSUE THREAD

**Issue by ChrWieg** [AWolf81/webextension_local_filesystem_links-native-host-binaries#2]
Hello, 

thanks a lot for the tool, it is very helpfull!
Could you please also provide the sources?
Thanks a lot
Christof

**Comment by ChrWieg** [comment]
Sorry I've found the sources: [https://github.com/feinstaub/webextension_local_filesystem_links/tree/dependabot/npm_and_yarn/test/webserver/open-6.0.0/native-host/src](url).

**Comment by AWolf81** [comment]
The source code of the native app is in the extension repo in subdirectory native-host.

It's a Python script.

https://github.com/feinstaub/webextension_local_filesystem_links/tree/master/native-host/src
